/**
 * Integer hundredths of a kilogram. For example, 12.30 kg is stored as 1230.
 * The brand prevents ordinary numbers from being passed to domain calculations.
 */
declare const kg100Brand: unique symbol

export type Kg100 = number & { readonly [kg100Brand]: 'Kg100' }

export type ShiftCode = 'DAY' | 'NIGHT'

export type ProductionDayStatus =
  | 'DRAFT'
  | 'IN_PROGRESS'
  | 'UNBALANCED'
  | 'BALANCED'
  | 'CLOSED'

export type ReconciliationStatus = 'BALANCED' | 'UNBALANCED'

export type ProductionProcess = 'PACKING' | 'FREEZING'

export type ProductionDayOperationMode = 'NORMAL' | 'BALANCE_ONLY'

export type ReferenceStatus =
  | 'AT_OR_ABOVE_REFERENCE'
  | 'BELOW_REFERENCE'
  | 'NOT_APPLICABLE'

export type SummaryValidationStatus = 'VALID' | 'INVALID'

export type SourceConfidence = 'EXPLICIT' | 'RECONCILED_INFERENCE'

export type IntegrityIssueCode =
  | 'RAW_MATERIAL_TOTAL_MISMATCH'
  | 'DUPLICATE_RAW_MATERIAL_ENTRY_ID'
  | 'DUPLICATE_PRODUCT_ID'
  | 'DUPLICATE_ADJUSTMENT_ID'
  | 'DUPLICATE_BALANCE_LOT_ID'
  | 'DUPLICATE_BALANCE_USE_ID'
  | 'NEGATIVE_QUANTITY'
  | 'INVALID_ADJUSTMENT_METADATA'
  | 'BALANCE_OVERUSED'
  | 'BALANCE_PRODUCT_NOT_FOUND'
  | 'BALANCE_FAMILY_MISMATCH'
  | 'BALANCE_ORIGIN_NOT_PREVIOUS'
  | 'NEGATIVE_OWN_PRODUCTION'
  | 'NUCA_WASH_AUTHORIZATION_MISSING'
  | 'NUCA_PRODUCTION_WITHOUT_ACTIVE_WASH'
  | 'DUPLICATE_PRODUCTION_DAY_ID'
  | 'DUPLICATE_PRODUCTION_DAY_DATE'
  | 'WEEK_DATE_OUT_OF_RANGE'
  | 'PRODUCT_METADATA_MISMATCH'

export type SummaryGroupId =
  | 'ALETA'
  | 'MANTO'
  | 'ANILLAS'
  | 'BOTON'
  | 'RECORTE_CRUDO'
  | 'RECORTE_COCIDO'
  | 'REJOS_SPECIAL'
  | 'REJOS'
  | 'REPRODUCTOR'
  | 'PICO'
  | 'NUCA_SEMILIMPIA'
  | 'NUCA_BIKINI'

export interface SourceReference {
  readonly sheet: string
  readonly cell: string
}

export interface AdjustmentRecord {
  readonly id: string
  readonly direction: 'INCREASE' | 'DECREASE'
  readonly kg100: Kg100
  readonly reason: string
  readonly userId: string
  readonly createdAt: string
}

export interface ShiftProductEntry {
  /** Physical quantity shown by the shift report, before explicit adjustments. */
  readonly reportedKg100: Kg100
  readonly adjustments: readonly AdjustmentRecord[]
}

export interface ProductionLine {
  readonly familyId: string
  readonly familyName: string
  readonly productId: string
  readonly productName: string
  /** Operational block used by the formulas in RESUMEN. */
  readonly summaryGroupId: SummaryGroupId
  readonly source: SourceReference
  readonly shiftBreakdownConfidence: SourceConfidence
  readonly shifts: Readonly<Record<ShiftCode, ShiftProductEntry>>
  /** Additional production coming from the tunnel, kept apart from supervisor reports. */
  readonly tunnelShifts?: Readonly<Record<ShiftCode, ShiftProductEntry>>
  readonly treatmentKg100: Kg100
  /** Balance generated by this production day, not unconsumed balance from an older day. */
  readonly newClosingBalanceKg100: Kg100
  /** Independent total from the product-finished table. */
  readonly declaredFinishedKg100: Kg100
}

export interface BalanceUse {
  readonly id: string
  readonly targetDayId: string
  readonly shift: ShiftCode
  readonly kg100: Kg100
}

export interface BalanceLot {
  readonly id: string
  /** Omitted historical lots belong to the Packing balance ledger. */
  readonly process?: ProductionProcess
  readonly originDayId: string
  readonly familyId: string
  readonly productId: string
  /** Ledger key retained when a legacy family-only balance is mapped to an exact product. */
  readonly sourceProductId?: string
  readonly originalKg100: Kg100
  readonly uses: readonly BalanceUse[]
}

export interface RawMaterialEntry {
  readonly id: string
  readonly kg100: Kg100
  /** The source formula does not identify the shift for its two addends. */
  readonly shift: ShiftCode | null
}

export interface NucaWashAuthorization {
  readonly kind: 'CUSTOMER_ORDER' | 'USER_CONFIRMED_ORDER'
  /** Order number when the source exposes it; null keeps the missing reference explicit. */
  readonly reference: string | null
  readonly reason: string
}

export interface ClosureObservationRecord {
  readonly closedAt: string
  readonly code: string
  readonly message: string
  readonly familyKey?: string
  readonly productId?: string
  readonly kg100?: Kg100
  readonly userId?: string
}

/** Optional common metadata reserved for a later productivity module. */
export interface OperationalPerformanceMetadata {
  readonly supervisor?: string
  readonly personnelCount?: number
  readonly startedAt?: string
  readonly finishedAt?: string
  readonly downtimeMinutes?: number
  readonly effectiveMinutes?: number
}

export interface IntegrityIssue {
  readonly code: IntegrityIssueCode
  readonly message: string
  readonly scope: 'DAY' | 'WEEK'
  readonly dayId?: string
  readonly productId?: string
  readonly balanceLotId?: string
  readonly shift?: ShiftCode
}

export interface ProductionDay {
  readonly id: string
  readonly date: string
  readonly displayName: string
  readonly status: ProductionDayStatus
  readonly createdAt?: string
  readonly updatedAt?: string
  /** Omitted historical records are Packing records for backward compatibility. */
  readonly process?: ProductionProcess
  readonly operationalPerformance?: OperationalPerformanceMetadata
  /** Preserves whether the web draft had every required capture field completed. */
  readonly captureRequiredDataComplete?: boolean
  /** Warnings accepted at closure time, kept as an auditable historical record. */
  readonly closureObservations?: readonly ClosureObservationRecord[]
  /** Sundays default to balance processing; omitted historical records remain normal. */
  readonly operationMode?: ProductionDayOperationMode
  readonly rawMaterialEntries: readonly RawMaterialEntry[]
  readonly declaredRawMaterialKg100: Kg100
  readonly declaredShiftTotalsKg100: Readonly<Record<ShiftCode, Kg100>>
  readonly declaredFinishedTotalKg100: Kg100
  /** Explicit condition for the optional Tunnel stage; undefined keeps historical days compatible. */
  readonly hasTunnelProduction?: boolean
  readonly lines: readonly ProductionLine[]
  readonly receivedBalanceLots: readonly BalanceLot[]
  readonly nucaWashAuthorization: NucaWashAuthorization | null
  readonly performanceReferenceBasisPoints: number
  readonly nucaBikiniReferenceBasisPoints: number
  /** Explicit allocation from the sheet; it must not be hidden in a formula. */
  readonly rawMaterialAllocationOverridesKg100: Readonly<
    Partial<Record<SummaryGroupId, Kg100>>
  >
}

export interface ShiftEntryCalculation {
  readonly reportedKg100: Kg100
  readonly adjustmentKg100: Kg100
  readonly previousBalanceProcessedKg100: Kg100
  readonly ownProductionKg100: Kg100
}

export interface ShiftCalculation extends ShiftEntryCalculation {
  readonly declaredReportedKg100: Kg100
  readonly detailDifferenceKg100: Kg100
}

export interface ProductReconciliation {
  readonly familyId: string
  readonly familyName: string
  readonly productId: string
  readonly productName: string
  readonly shiftBreakdownConfidence: SourceConfidence
  readonly day: ShiftEntryCalculation
  readonly night: ShiftEntryCalculation
  readonly tunnel: Readonly<Record<ShiftCode, ShiftEntryCalculation>>
  readonly productiveDayKg100: Kg100
  readonly productiveNightKg100: Kg100
  readonly treatmentKg100: Kg100
  readonly newClosingBalanceKg100: Kg100
  readonly expectedFinishedKg100: Kg100
  readonly declaredFinishedKg100: Kg100
  readonly differenceKg100: Kg100
}

export interface WeeklySummaryPeriod {
  readonly startDate: string
  readonly endDate: string
}

export interface PerformanceResult {
  readonly ratio: number | null
  readonly percent: number | null
  readonly referencePercent: number
  readonly status: ReferenceStatus
}

export interface NucaReferenceResult {
  readonly applicable: boolean
  readonly applicableRawMaterialKg100: Kg100
  readonly actualKg100: Kg100
  readonly referenceKg100: Kg100
  readonly varianceKg100: Kg100
  readonly shareOfRawMaterialPercent: number | null
  readonly referencePercent: number
  readonly status: ReferenceStatus
}

export type NucaBikiniReferenceResult = NucaReferenceResult

export interface ProductionDayCalculation {
  readonly day: ShiftCalculation
  readonly night: ShiftCalculation
  /** Normal report production after deducting processed previous balances. */
  readonly reportOwnProductionKg100: Kg100
  readonly tunnel: {
    readonly dayKg100: Kg100
    readonly nightKg100: Kg100
    readonly totalKg100: Kg100
  }
  /** Report production after balances plus the tunnel movement for the shift. */
  readonly productiveDayKg100: Kg100
  readonly productiveNightKg100: Kg100
  /** Sum of productive Day and Night, including Tunnel exactly once. */
  readonly ownTurnProductionKg100: Kg100
  readonly treatmentKg100: Kg100
  readonly newClosingBalanceKg100: Kg100
  readonly expectedFinishedKg100: Kg100
  readonly declaredFinishedKg100: Kg100
  readonly calculatedClosingBalanceKg100: Kg100
  readonly receivedPreviousBalanceKg100: Kg100
  readonly processedPreviousBalanceKg100: Kg100
  readonly pendingPreviousBalanceKg100: Kg100
  readonly differenceKg100: Kg100
  readonly status: ReconciliationStatus
  readonly performance: PerformanceResult
  readonly nucaSemilimpia: NucaReferenceResult
  readonly nucaBikini: NucaBikiniReferenceResult
  readonly products: readonly ProductReconciliation[]
  readonly integrityIssues: readonly IntegrityIssue[]
}

export interface BalancePosition {
  readonly originalKg100: Kg100
  readonly processedDayKg100: Kg100
  readonly processedNightKg100: Kg100
  readonly processedTotalKg100: Kg100
  readonly pendingKg100: Kg100
  readonly overusedKg100: Kg100
  readonly isValid: boolean
}

export interface OutstandingBalancePosition {
  readonly originDayId: string
  readonly originDate: string
  readonly familyId: string
  readonly familyName: string
  readonly productId: string
  readonly productName: string
  readonly generatedKg100: Kg100
  readonly processedDayKg100: Kg100
  readonly processedNightKg100: Kg100
  readonly processedTotalKg100: Kg100
  readonly pendingKg100: Kg100
  /** Consumed above what the origin generated; kept apart from `pendingKg100`. */
  readonly excessKg100: Kg100
}

export interface WeeklyProductTotal {
  readonly familyId: string
  readonly familyName: string
  readonly productId: string
  readonly productName: string
  readonly summaryGroupId: SummaryGroupId
  readonly totalKg100: Kg100
}

export interface WeeklyGroupTotal {
  readonly summaryGroupId: SummaryGroupId
  readonly totalKg100: Kg100
  readonly shareOfRawMaterialPercent: number | null
}

export interface RawMaterialDistribution {
  readonly tubeKg100: Kg100
  readonly aletaKg100: Kg100
  readonly rejosKg100: Kg100
  readonly nucasKg100: Kg100
}

export interface WeeklySummary {
  readonly rawMaterialKg100: Kg100
  readonly distribution: RawMaterialDistribution
  readonly productTotals: readonly WeeklyProductTotal[]
  readonly productTotalsById: Readonly<Record<string, Kg100>>
  readonly groupTotals: readonly WeeklyGroupTotal[]
  readonly detailFinishedKg100: Kg100
  readonly declaredFinishedKg100: Kg100
  /** Same orientation as RESUMEN!D108: daily totals minus product detail. */
  readonly differenceKg100: Kg100
  readonly status: SummaryValidationStatus
  readonly allDaysBalanced: boolean
  readonly performance: PerformanceResult
  readonly nucaSemilimpia: NucaReferenceResult
  readonly nucaBikini: NucaBikiniReferenceResult
  readonly days: readonly ProductionDayCalculation[]
  readonly integrityIssues: readonly IntegrityIssue[]
}
